export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Contact } from "./Contact";
export { default as Navbar } from "./Navbar";
export { default as Title } from "./Title";
export { default as Footer } from "./Footer";
export { default as Logo } from "./Logo";
export { default as Sidebar } from "./Sidebar";
